# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/data.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'schema/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11schema/data.proto\"5\n\x05Power\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x02\x12\x0f\n\x07voltage\x18\x03 \x01(\x02\"B\n\x08Steering\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x16\n\x0e\x62rake_pressure\x18\x02 \x01(\x02\x12\x12\n\nturn_angle\x18\x03 \x01(\x02\":\n\x07RpmAxle\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x10\n\x08rpm_left\x18\x02 \x01(\x02\x12\x11\n\trpm_right\x18\x03 \x01(\x02\"4\n\x03Gps\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x0f\n\x07gps_lat\x18\x02 \x01(\x02\x12\x10\n\x08gps_long\x18\x03 \x01(\x02\"2\n\x05Motor\x12\n\n\x02ts\x18\x01 \x01(\r\x12\x0b\n\x03rpm\x18\x02 \x01(\x02\x12\x10\n\x08throttle\x18\x03 \x01(\x02\"\xc0\x01\n\x07Sensors\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x11\n\tglobal_ts\x18\x02 \x01(\x04\x12\x15\n\x05power\x18\x03 \x01(\x0b\x32\x06.Power\x12\x1b\n\x08steering\x18\x04 \x01(\x0b\x32\t.Steering\x12\x1b\n\trpm_front\x18\x05 \x01(\x0b\x32\x08.RpmAxle\x12\x1a\n\x08rpm_back\x18\x06 \x01(\x0b\x32\x08.RpmAxle\x12\x11\n\x03gps\x18\x07 \x01(\x0b\x32\x04.Gps\x12\x15\n\x05motor\x18\x08 \x01(\x0b\x32\x06.Motorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POWER']._serialized_start=21
  _globals['_POWER']._serialized_end=74
  _globals['_STEERING']._serialized_start=76
  _globals['_STEERING']._serialized_end=142
  _globals['_RPMAXLE']._serialized_start=144
  _globals['_RPMAXLE']._serialized_end=202
  _globals['_GPS']._serialized_start=204
  _globals['_GPS']._serialized_end=256
  _globals['_MOTOR']._serialized_start=258
  _globals['_MOTOR']._serialized_end=308
  _globals['_SENSORS']._serialized_start=311
  _globals['_SENSORS']._serialized_end=503
# @@protoc_insertion_point(module_scope)
